[package]
name = "rgpui-3d"
description = "scenekit 3D 渲染引擎的 rgpui 集成，支持 3D 场景渲染和合成"
publish=true
license = "Apache-2.0"
version.workspace = true
edition.workspace = true
repository = "https://github.com/launcher-rs/rgpui"

[features]
default = ["shared-wgpu"]
scenekit-renderer = ["scenekit/renderer", "scenekit/loader"]
shared-wgpu = ["dep:rgpui-wgpu"]

[dependencies]
rgpui = { workspace = true }
scenekit = { path = "../../../scenekit/crates/scenekit", features = ["renderer", "loader"] }
wgpu = { workspace = true }
image = { workspace = true }
bytemuck.workspace = true
gltf = "1.4"
smallvec = { workspace = true }
rgpui-wgpu = { workspace = true, optional = true }

[dev-dependencies]
rgpui-platform = { workspace = true, features = ["font-kit", "wayland", "x11"] }
pollster = { workspace = true }
smol = { workspace = true }
rfd = "0.17"

[[example]]
name = "scenekit_cube"
path = "examples/scenekit_cube.rs"

[[example]]
name = "scenekit_model"
path = "examples/scenekit_model.rs"

[[example]]
name = "scenekit_skin"
path = "examples/scenekit_skin.rs"

[lints]
workspace = true
