use proc_macro::TokenStream;
use proc_macro2::{Ident, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::parse_macro_input;

/// 处理 `register_action!` 过程宏的入口函数。
///
/// 该函数接收类型名称，生成动作注册代码并将其提交到 GPUI 的 inventory 系统中。
pub(crate) fn register_action(ident: TokenStream) -> TokenStream {
    let name = parse_macro_input!(ident as Ident);
    let registration = generate_register_action(&name);

    TokenStream::from(quote! {
        #registration
    })
}

/// 生成动作注册代码的核心函数。
///
/// 该函数为指定类型生成：
/// 1. 一个隐藏的 `__autogenerated()` 方法
/// 2. 一个动作构建器函数，收集动作的元数据（名称、类型 ID、构建函数等）
/// 3. 使用 `inventory::submit!` 将动作构建器注册到全局 inventory 中
///
/// # 参数
///
/// * `type_name` - 要注册的动作类型名称
pub(crate) fn generate_register_action(type_name: &Ident) -> TokenStream2 {
    let action_builder_fn_name = format_ident!(
        "__gpui_actions_builder_{}",
        type_name.to_string().to_lowercase()
    );

    quote! {
        impl #type_name {
            /// 这是自动生成的函数，请勿使用。
            #[automatically_derived]
            #[doc(hidden)]
            fn __autogenerated() {
                /// 这是自动生成的函数，请勿使用。
                #[doc(hidden)]
                fn #action_builder_fn_name() -> rgpui::MacroActionData {
                    rgpui::MacroActionData {
                        name: <#type_name as rgpui::Action>::name_for_type(),
                        type_id: ::std::any::TypeId::of::<#type_name>(),
                        build: <#type_name as rgpui::Action>::build,
                        json_schema: <#type_name as rgpui::Action>::action_json_schema,
                        deprecated_aliases: <#type_name as rgpui::Action>::deprecated_aliases(),
                        deprecation_message: <#type_name as rgpui::Action>::deprecation_message(),
                        documentation: <#type_name as rgpui::Action>::documentation(),
                    }
                }

                rgpui::private::inventory::submit! {
                    rgpui::MacroActionBuilder(#action_builder_fn_name)
                }
            }
        }
    }
}
