[package]
name = "tokio_example"
version = "0.1.0"
edition = "2024"
publish = false

[features]
reqwest = ["dep:reqwest", "rgpui/reqwest"]

[dependencies]
rgpui = { workspace = true, features = ["tokio"] }
rgpui-platform.workspace = true
anyhow.workspace = true
reqwest = { workspace = true, optional = true }
tokio.workspace = true
