[package]
name = "rgpui-web"
version.workspace = true
edition.workspace = true
publish = true
description = "Web/WASM 平台实现"
license = "Apache-2.0"
autoexamples = false
repository = "https://github.com/launcher-rs/rgpui"

[lints]
workspace = true

[features]
default = ["multithreaded"]
multithreaded = ["dep:wasm_thread"]

[lib]
path = "src/rgpui_web.rs"

[target.'cfg(target_family = "wasm")'.dependencies]
rgpui = { workspace = true, features = ["dom-backend"] }
rgpui-dom.workspace = true
parking_lot = { workspace = true, features = ["nightly"] }
rgpui-wgpu.workspace = true
anyhow.workspace = true
futures.workspace = true
log.workspace = true
smallvec.workspace = true
uuid.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-time.workspace = true
console_error_panic_hook.workspace = true
js-sys.workspace = true
raw-window-handle.workspace = true
wasm_thread = { git = "https://github.com/zed-industries/wasm_thread", rev = "0cf96c7708dfb97ccf3da50347e25edcf75d6937", version = "0.3", features = [
    "es_modules",
], optional = true }
web-sys = { workspace = true, features = [
    "console",
    "ClipboardEvent",
    "CompositionEvent",
    "CssStyleDeclaration",
    "DataTransfer",
    "Document",
    "DomRect",
    "DragEvent",
    "Element",
    "EventTarget",
    "File",
    "FileList",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "KeyboardEvent",
    "MediaQueryList",
    "MediaQueryListEvent",
    "MouseEvent",
    "Navigator",
    "PointerEvent",
    "ResizeObserver",
    "ResizeObserverBoxOptions",
    "ResizeObserverEntry",
    "ResizeObserverSize",
    "ResizeObserverOptions",
    "Screen",
    "Storage",
    "VisualViewport",
    "Headers",
    "HtmlTextAreaElement",
    "Request",
    "RequestInit",
    "RequestRedirect",
    "Response",
    "WheelEvent",
    "Window",
] }
